version: "3.9"
services:
  backend:
    build: .
    working_dir: /src/app/server
    command: npm run dev
    environment:
      - PORT=4000
    ports:
      - "4000:4000"

  frontend:
    build: .
    working_dir: /src/app/client
    command: npm run dev
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
